name: imp-project
services:
- name: web
  source_dir: /
  github:
    repo: tanishsabane07/IMPing
    branch: main
  run_command: cd server && npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: MONGODB_URI
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: JWT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
- name: static-site
  source_dir: /client
  github:
    repo: tanishsabane07/IMPing
    branch: main
  build_command: npm install && npm run build
  output_dir: dist
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
